### ISSUE TITLE
The xinetd module should not manage files if $package_ensure == absent

### ISSUE THREAD

**Issue by trevor-vaughan** [simp/pupmod-simp-xinetd#66]
Ported over from PR creation by @bschonec in #65.

> When uninstalling the xinetd package, this module attempts to manage /etc/xined.conf, /etc/xinetd.d/ files and attempts (in vain) to start the xinetd service.
> 
> I couldn't figure out how to open a new issue so I've commented the init.pp file appropriately and am asking for comments on this issue.
> 
> I have about 50 servers that need xinetd with the exception of one. In the node's YAML file, I've put "xinetd::package_ensure: absent" and the module fails because it's trying to manage the xinetd files when it shouldn't.
> 
> Yes, I realize I could write a conditional check NOT to include ::xinetd::service but then I'd eventually have spaghetti code trying to work around the module's bug. I'm kind of a purist and believe that the module should do no harm even when it's called and the packages don't need to be installed.
>

**Comment by trevor-vaughan** [comment]
@bschonec can you see if the PR in #67 does what you expect?

**Comment by bschonec** [comment]
Not yet.  With the xinetd service running, the changes submitted result in a puppet errors:

`Notice: /Stage[main]/Xinetd/Package[xinetd]/ensure: removed (corrective)
Notice: /Stage[main]/Xinetd/File[/etc/xinetd.conf]/ensure: defined content as '{sha256}e5a385d3997cc6501049df0016fb693af8f975da686450d731e7e3b57d79d20c' (corrective)
Info: /Stage[main]/Xinetd/File[/etc/xinetd.conf]: Scheduling refresh of Service[xinetd]
Error: Systemd start for xinetd failed!
journalctl log for xinetd:
-- Logs begin at Fri 2022-05-20 07:55:06 EDT, end at Fri 2022-05-20 15:54:53 EDT. --
May 20 15:50:48 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Stopping Xinetd A Powerful Replacement For Inetd...
May 20 15:50:48 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Stopped Xinetd A Powerful Replacement For Inetd.
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Starting Xinetd A Powerful Replacement For Inetd...
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Started Xinetd A Powerful Replacement For Inetd.
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/chargen-dgram [file=/etc/xinetd.conf] [line=13]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/chargen-stream [file=/etc/xinetd.d/chargen-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/daytime-dgram [file=/etc/xinetd.d/daytime-dgram] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/daytime-stream [file=/etc/xinetd.d/daytime-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/discard-dgram [file=/etc/xinetd.d/discard-dgram] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/discard-stream [file=/etc/xinetd.d/discard-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/echo-dgram [file=/etc/xinetd.d/echo-dgram] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/echo-stream [file=/etc/xinetd.d/echo-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/tcpmux-server [file=/etc/xinetd.d/tcpmux-server] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/telnetkrft705 [file=/etc/xinetd.d/telnetkrft705] [line=68]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/time-dgram [file=/etc/xinetd.d/time-dgram] [line=20]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/time-stream [file=/etc/xinetd.d/time-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing chargen
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing chargen
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing daytime
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing daytime
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing discard
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing discard
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing echo
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing echo
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing tcpmux
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing time
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing time
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: xinetd Version 2.3.15 started with loadavg labeled-networking options compiled in.
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Started working: 1 available service
May 20 15:51:57 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Stopping Xinetd A Powerful Replacement For Inetd...
May 20 15:51:57 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: unexpected signal: 18 (Continued) in signal pipe
May 20 15:51:57 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Exiting...
May 20 15:51:57 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Stopped Xinetd A Powerful Replacement For Inetd.
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Starting Xinetd A Powerful Replacement For Inetd...
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/chargen-dgram [file=/etc/xinetd.conf] [line=13]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/chargen-stream [file=/etc/xinetd.d/chargen-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Started Xinetd A Powerful Replacement For Inetd.
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/daytime-dgram [file=/etc/xinetd.d/daytime-dgram] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/daytime-stream [file=/etc/xinetd.d/daytime-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/discard-dgram [file=/etc/xinetd.d/discard-dgram] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/discard-stream [file=/etc/xinetd.d/discard-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/echo-dgram [file=/etc/xinetd.d/echo-dgram] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/echo-stream [file=/etc/xinetd.d/echo-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/tcpmux-server [file=/etc/xinetd.d/tcpmux-server] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/telnetkrft705 [file=/etc/xinetd.d/telnetkrft705] [line=68]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/time-dgram [file=/etc/xinetd.d/time-dgram] [line=20]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/time-stream [file=/etc/xinetd.d/time-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: removing chargen
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: removing chargen
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: removing daytime

Error: /Stage[main]/Xinetd/Service[xinetd]/ensure: change from 'stopped' to 'running' failed: Systemd start for xinetd failed!
journalctl log for xinetd:
-- Logs begin at Fri 2022-05-20 07:55:06 EDT, end at Fri 2022-05-20 15:54:53 EDT. --
May 20 15:50:48 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Stopping Xinetd A Powerful Replacement For Inetd...
May 20 15:50:48 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Stopped Xinetd A Powerful Replacement For Inetd.
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Starting Xinetd A Powerful Replacement For Inetd...
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Started Xinetd A Powerful Replacement For Inetd.
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/chargen-dgram [file=/etc/xinetd.conf] [line=13]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/chargen-stream [file=/etc/xinetd.d/chargen-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/daytime-dgram [file=/etc/xinetd.d/daytime-dgram] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/daytime-stream [file=/etc/xinetd.d/daytime-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/discard-dgram [file=/etc/xinetd.d/discard-dgram] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/discard-stream [file=/etc/xinetd.d/discard-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/echo-dgram [file=/etc/xinetd.d/echo-dgram] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/echo-stream [file=/etc/xinetd.d/echo-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/tcpmux-server [file=/etc/xinetd.d/tcpmux-server] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/telnetkrft705 [file=/etc/xinetd.d/telnetkrft705] [line=68]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/time-dgram [file=/etc/xinetd.d/time-dgram] [line=20]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Reading included configuration file: /etc/xinetd.d/time-stream [file=/etc/xinetd.d/time-stream] [line=67]
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing chargen
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing chargen
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing daytime
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing daytime
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing discard
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing discard
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing echo
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing echo
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing tcpmux
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing time
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: removing time
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: xinetd Version 2.3.15 started with loadavg labeled-networking options compiled in.
May 20 15:51:53 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Started working: 1 available service
May 20 15:51:57 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Stopping Xinetd A Powerful Replacement For Inetd...
May 20 15:51:57 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: unexpected signal: 18 (Continued) in signal pipe
May 20 15:51:57 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22834]: Exiting...
May 20 15:51:57 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Stopped Xinetd A Powerful Replacement For Inetd.
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Starting Xinetd A Powerful Replacement For Inetd...
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/chargen-dgram [file=/etc/xinetd.conf] [line=13]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/chargen-stream [file=/etc/xinetd.d/chargen-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com systemd[1]: Started Xinetd A Powerful Replacement For Inetd.
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/daytime-dgram [file=/etc/xinetd.d/daytime-dgram] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/daytime-stream [file=/etc/xinetd.d/daytime-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/discard-dgram [file=/etc/xinetd.d/discard-dgram] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/discard-stream [file=/etc/xinetd.d/discard-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/echo-dgram [file=/etc/xinetd.d/echo-dgram] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/echo-stream [file=/etc/xinetd.d/echo-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/tcpmux-server [file=/etc/xinetd.d/tcpmux-server] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/telnetkrft705 [file=/etc/xinetd.d/telnetkrft705] [line=68]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/time-dgram [file=/etc/xinetd.d/time-dgram] [line=20]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: Reading included configuration file: /etc/xinetd.d/time-stream [file=/etc/xinetd.d/time-stream] [line=67]
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: removing chargen
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: removing chargen
May 20 15:51:58 kraft-mmc.krft705.usva0017.oraclevcn.com xinetd[22867]: removing daytime
 (corrective)
Notice: /Stage[main]/Xinetd/Service[xinetd]: Triggered 'refresh' from 1 event
Info: Class[Xinetd]: Unscheduling all events on Class[Xinetd]`

But it's entirely possible that my test server is so screwed up that the module is failing.

**Comment by trevor-vaughan** [comment]
@bschonec It seems unlikely that this change could cause that. The gist of the change is that, if the package is to be removed, that's the only thing that puppet will touch. Everything else is disabled.

**Comment by bschonec** [comment]
Indeed @trevor-vaughan you are correct.  I had a typo in my Puppet file that was preventing R10k from pulling down your branch and Puppet was still using my crappy branh.

Your branch does fix the problems that I was experiencing.

Thank for submitting the code.
